### ISSUE TITLE
Failed to load SSH server

### ISSUE THREAD

**Issue by bvk** [belak/go-gitdir#20]
I get the following error:

```
bvk@milk:~$ GITDIR_BASE_DIR=/tmp/git ~/go/bin/go-gitdir serve
{"level":"info","time":"2019-10-30T15:27:47-07:00","message":"Starting go-git-dir"}
{"level":"info","time":"2019-10-30T15:27:47-07:00","message":"Reloading"}
{"level":"fatal","error":"ssh: unsupported key type ed25519.PublicKey","time":"2019-10-30T15:27:47-07:00","message":"Failed to load SSH server"}
bvk@milk:~$

bvk@milk:/tmp/git/admin/admin$ git log
commit e24c9cd7a1fe75a6d14b93b36261f08c2770c2a0
Author: root <root@localhost>
Date:   Wed Oct 30 15:26:33 2019 -0700

    Updated ssh keys

commit a608461d301832d3bd9996c962be9e12511157e0
Author: root <root@localhost>
Date:   Wed Oct 30 15:25:36 2019 -0700

    Updated user bvk

commit 094ad53a02c79bf3917c05c3dc7dc18a5cfba829
Author: root <root@localhost>
Date:   Wed Oct 30 15:25:10 2019 -0700

    Updated user bvk
bvk@milk:/tmp/git/admin/admin$
```

**Comment by belak** [comment]
What version of go did you use to build go-gitdir?

**Comment by belak** [comment]
The short version of this is that it will probably fail on < go 1.13 because they moved the ed25519 package into the standard library.

https://golang.org/doc/go1.13#crypto/ed25519

**Comment by bvk** [comment]
I am pretty sure I was using go 1.13.

```
bvk@milk:~$ go version
go version go1.13 linux/amd64
bvk@milk:~$ go version ~/go/bin/go-gitdir
/home/bvk/go/bin/go-gitdir: go1.13
bvk@milk:~$
```

**Comment by belak** [comment]
How did you install it? Did you use go get or clone and go build? I'll play with this some when I get home and see if I can reproduce it.

**Comment by bvk** [comment]
I installed using `go get github.com/belak/go-gitdir`.

**Comment by belak** [comment]
I've heard that go get doesn't properly take go modules into account. I'll have to see if I can reproduce it.

**Comment by belak** [comment]
I finally managed to reproduce this. Here is what I've tried:

- `go get github.com/belak/go-gitdir`
- Creating a package which purposefully switches between x/crypto/ed25519 and crypto/ed25519 and loads them in gossh.
- Purposefully trying to use the wrong import when creating the keys.
- Downgrading x/crypto/ssh to a version before it was a wrapper for crypto/ssh (this is what finally triggered it)

In short, I think you may have downloaded a package using go get in the past which used x/crypto... so this is on an older version. Using `go get` does appear to ignore go modules, so those two things together resulted in go-gitdir being built against an older version of x/crypto which was incompatible with the new crypto/ed25519 package.

The easiest way to build this package is to clone it somewhere (outside your GOPATH) and run `go build`. This should use the modules file and pull in a working version of x/crypto/ssh and x/crypto/ed25519.

If this doesn't work, I'm happy to investigate further.

**Comment by belak** [comment]
I've also pushed a change which is a little more careful about using x/crypto/ed25519 (which should work, even in the case of an older version of x/crypto.

**Comment by bvk** [comment]
Thanks.  I will try tonight and will let you know.

**Comment by bvk** [comment]
Yeah, it seems to work if built from the git checkout directory.  There is no GUI page when I visit :2222 -- some page with stats would be nice to have.
